import { api, type CompanyProfile } from "@/lib/api";
export type { CompanyProfile } from "@/lib/api";
export type CompanyProfileInput = Omit<CompanyProfile, "user_id">;
export const getCompanyProfile = async () => (await api<{ profile: CompanyProfile | null }>("/api/profile")).profile;
export const upsertCompanyProfile = async (profile: CompanyProfileInput) => (await api<{ profile: CompanyProfile }>("/api/profile", { method:"PUT", body:JSON.stringify(profile) })).profile;
export const INDUSTRIES = ["Software", "SaaS", "Consulting", "Healthcare", "Finance", "Marketing", "Real Estate", "Education", "Manufacturing", "Other"];
export const PRICE_RANGES = ["<$100", "$100–$500", "$500–$2,000", "$2,000–$10,000", "$10,000+"];
export const COMPANY_SIZES = ["1-10", "11-50", "51-200", "201-500", "501-1000", "1000+"];
export const TARGET_TITLES = ["CEO", "CTO", "CMO", "VP Sales", "VP Marketing", "Director", "Manager", "Founder", "Owner"];
export const REGIONS = ["North America", "Europe", "Latin America", "Africa", "Middle East", "Asia Pacific"];
