import type { Database } from "@/integrations/supabase/types";

type LeadSeed = Omit<
  Database["public"]["Tables"]["leads"]["Insert"],
  "user_id" | "id" | "is_demo" | "created_at" | "updated_at"
>;

/** Realistic sample leads spread across pipeline stages, scores and deal values. */
export const DEMO_LEADS: LeadSeed[] = [
  {
    name: "Amara Okafor",
    email: "amara@northwind-logistics.com",
    company: "Northwind Logistics",
    job_title: "VP of Sales",
    lead_score: 86,
    status: "replied",
    deal_value: 24000,
    location: "Lagos, Nigeria",
    bio: "Leads a 14-person outbound team scaling into East African freight corridors.",
    notes: "Replied asking about CRM integrations. Wants a demo with her ops lead.",
    social_links: { linkedin: "https://www.linkedin.com/in/amara-okafor-demo" },
  },
  {
    name: "Daniel Weiss",
    email: "d.weiss@heliosanalytics.io",
    company: "Helios Analytics",
    job_title: "Chief Revenue Officer",
    lead_score: 92,
    status: "meeting",
    deal_value: 48000,
    location: "Berlin, Germany",
    bio: "Owns revenue for a Series B analytics platform; replacing a legacy sales stack.",
    notes: "Meeting booked for next Tuesday. Bring ROI benchmarks.",
    social_links: { linkedin: "https://www.linkedin.com/in/daniel-weiss-demo" },
  },
  {
    name: "Priya Raman",
    email: "priya.raman@quantleaf.com",
    company: "Quantleaf",
    job_title: "Head of Growth",
    lead_score: 78,
    status: "proposal",
    deal_value: 31500,
    location: "Bengaluru, India",
    bio: "Growth lead focused on outbound experimentation and lifecycle messaging.",
    notes: "Proposal sent — awaiting procurement sign-off.",
    social_links: { twitter: "https://x.com/priyaraman-demo" },
  },
  {
    name: "Tom Fitzgerald",
    email: "tom@fitzgeraldbuilders.co",
    company: "Fitzgerald Builders",
    job_title: "Owner",
    lead_score: 71,
    status: "contacted",
    deal_value: 9000,
    location: "Dublin, Ireland",
    bio: "Runs a regional construction firm selling into commercial developers.",
    notes: "First touch sent. Follow up in 3 days.",
    social_links: {},
  },
  {
    name: "Sofia Marchetti",
    email: "sofia@velatextiles.it",
    company: "Vela Textiles",
    job_title: "Sales Director",
    lead_score: 64,
    status: "new",
    deal_value: 12000,
    location: "Milan, Italy",
    bio: "Directs a six-rep team selling sustainable fabrics to European brands.",
    notes: "Sourced from a trade directory. No outreach yet.",
    social_links: { website: "https://velatextiles.example.com" },
  },
  {
    name: "Kwame Mensah",
    email: "kwame.mensah@accrafintech.com",
    company: "Accra Fintech",
    job_title: "Co-founder & CEO",
    lead_score: 95,
    status: "won",
    deal_value: 60000,
    location: "Accra, Ghana",
    bio: "Founder of a payments startup expanding across West Africa.",
    notes: "Closed on the Pro annual plan. Great referral source.",
    social_links: { linkedin: "https://www.linkedin.com/in/kwame-mensah-demo" },
  },
  {
    name: "Elena Petrova",
    email: "elena.petrova@brightloop.dev",
    company: "Brightloop",
    job_title: "Engineering Manager",
    lead_score: 52,
    status: "lost",
    deal_value: 8000,
    location: "Tallinn, Estonia",
    bio: "Manages platform engineering; not the buyer for sales tooling.",
    notes: "Wrong persona — asked us to reach out to their RevOps lead instead.",
    social_links: { github: "https://github.com/brightloop-demo" },
  },
  {
    name: "Marcus Cole",
    email: "marcus@summitpeakmedia.com",
    company: "Summit Peak Media",
    job_title: "Business Development Manager",
    lead_score: 68,
    status: "interested",
    deal_value: 15000,
    location: "Denver, USA",
    bio: "Handles new business for a mid-market media agency.",
    notes: "Asked for pricing and a case study in his vertical.",
    social_links: { linkedin: "https://www.linkedin.com/in/marcus-cole-demo" },
  },
];
