import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Loader2, ArrowLeft } from "lucide-react";
import { toast } from "sonner";
import { auth } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";

export const Route = createFileRoute("/auth")({ component: AuthPage });
function AuthPage() {
  const navigate = useNavigate(); const [tab,setTab] = useState<"signin"|"signup">("signin");
  useEffect(() => { auth.me().then(() => navigate({to:"/dashboard",replace:true})).catch(() => undefined); }, [navigate]);
  return <div className="min-h-screen bg-[#f8faff] px-6 py-12"><div className="mx-auto flex min-h-[80vh] max-w-md flex-col justify-center"><Link to="/" className="mb-8 flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="h-4 w-4"/> Back to home</Link><div className="mb-6 flex items-center gap-2"><img src="/app-icon.png" alt="SalesGenius AI" className="h-9 w-9 rounded-lg"/><span className="text-lg font-semibold">SalesGenius AI</span></div><div className="rounded-2xl border bg-card p-8 shadow-[var(--shadow-elegant)]"><Tabs value={tab} onValueChange={(v)=>setTab(v as typeof tab)}><TabsList className="grid w-full grid-cols-2"><TabsTrigger value="signin">Sign in</TabsTrigger><TabsTrigger value="signup">Create account</TabsTrigger></TabsList><TabsContent value="signin"><Login/></TabsContent><TabsContent value="signup"><Signup/></TabsContent></Tabs></div></div></div>;
}
function Login() { const navigate=useNavigate(); const [email,setEmail]=useState(""); const [password,setPassword]=useState(""); const [loading,setLoading]=useState(false); const [resetting,setResetting]=useState(false); async function submit(e:React.FormEvent){e.preventDefault();setLoading(true);try{await auth.login({email,password});toast.success("Welcome back.");navigate({to:"/dashboard",replace:true});}catch(e){toast.error(e instanceof Error?e.message:"Could not sign in.");}finally{setLoading(false);}} async function reset(){if(!email){toast.error("Enter your email first.");return;}setResetting(true);try{await auth.forgotPassword(email);toast.success("If that account exists, a reset link is on its way.");}catch(e){toast.error(e instanceof Error?e.message:"Could not request reset.");}finally{setResetting(false);}} return <form onSubmit={submit} className="mt-6 space-y-4"><div><Label>Email address</Label><Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5" placeholder="you@company.com"/></div><div><div className="flex justify-between"><Label>Password</Label><button type="button" className="text-xs text-primary hover:underline" onClick={reset} disabled={resetting}>{resetting?"Sending…":"Forgot password?"}</button></div><Input type="password" required autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5"/></div><Button className="w-full" disabled={loading}>{loading&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Sign in</Button></form>; }
function Signup() { const navigate=useNavigate(); const [fullName,setFullName]=useState("");const [companyName,setCompanyName]=useState("");const [email,setEmail]=useState("");const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [loading,setLoading]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();if(password!==confirm)return toast.error("Passwords do not match.");setLoading(true);try{await auth.signup({email,password,fullName,companyName});toast.success("Your account is ready. Let’s personalize it.");navigate({to:"/onboarding",replace:true});}catch(e){toast.error(e instanceof Error?e.message:"Could not create account.");}finally{setLoading(false);}} return <form onSubmit={submit} className="mt-6 space-y-4"><div><Label>Your name</Label><Input required value={fullName} onChange={e=>setFullName(e.target.value)} className="mt-1.5" placeholder="Alex Rivera"/></div><div><Label>Company</Label><Input value={companyName} onChange={e=>setCompanyName(e.target.value)} className="mt-1.5" placeholder="Acme Inc."/></div><div><Label>Work email</Label><Input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} className="mt-1.5" placeholder="you@company.com"/></div><div><Label>Create a password</Label><Input type="password" required minLength={10} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} className="mt-1.5" placeholder="At least 10 characters"/></div><div><Label>Confirm password</Label><Input type="password" required minLength={10} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} className="mt-1.5"/></div><Button className="w-full" disabled={loading}>{loading&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Create account</Button></form>; }
