import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useState } from "react";
import { ArrowLeft, Loader2, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { auth } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
export const Route = createFileRoute("/reset-password")({ component: ResetPasswordPage });
function ResetPasswordPage(){const navigate=useNavigate();const [password,setPassword]=useState("");const [confirm,setConfirm]=useState("");const [saving,setSaving]=useState(false);const token=new URLSearchParams(location.search).get("token");async function submit(e:React.FormEvent){e.preventDefault();if(!token)return toast.error("This reset link is incomplete.");if(password!==confirm)return toast.error("Passwords do not match.");setSaving(true);try{await auth.resetPassword(token,password);toast.success("Password updated. Please sign in.");navigate({to:"/auth",replace:true});}catch(e){toast.error(e instanceof Error?e.message:"Could not reset password.");}finally{setSaving(false);}}return <div className="min-h-screen bg-[#f8faff] px-6 py-12"><div className="mx-auto flex min-h-[80vh] max-w-md flex-col justify-center"><Link to="/auth" className="mb-8 flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="h-4 w-4"/>Back to sign in</Link><div className="rounded-2xl border bg-card p-8"><div className="mb-6 flex items-center gap-2"><ShieldCheck className="h-5 w-5 text-primary"/><div><h1 className="font-semibold">Choose a new password</h1><p className="text-xs text-muted-foreground">Use at least 10 characters.</p></div></div><form onSubmit={submit} className="space-y-4"><div><Label>New password</Label><Input className="mt-1.5" type="password" minLength={10} required value={password} onChange={e=>setPassword(e.target.value)}/></div><div><Label>Confirm password</Label><Input className="mt-1.5" type="password" minLength={10} required value={confirm} onChange={e=>setConfirm(e.target.value)}/></div><Button className="w-full" disabled={saving||!token}>{saving&&<Loader2 className="mr-2 h-4 w-4 animate-spin"/>}Update password</Button></form></div></div></div>}
